spring:
  security:
    oauth2:
      client:
        registration:
          subscriptionopsclient:
            authorization-grant-type: client_credentials
            client-id: subscriptionopsclient
            client-secret: subscriptionopsclient_secret
        provider:
          subscriptionopsclient:
            token-uri: https://localhost:8443/oauth/token
  cloud:
    stream:
      bindings:
        orderCreatedInputSubscriptionOperations:
          group: subscription-operations-order-created
          destination: orderCreated
        subscriptionCreatedOutput:
          destination: subscriptionCreated
broadleaf:
  database:
    provider: none
  transitionrequest:
    enabled: false
  changesummary:
    notification:
      active: false
  tracking:
    sandbox:
      purge:
        enabled: false
    notification:
      prune:
        active: false
  purge:
    message:
      lock:
        active: false